#!/bin/bash
#Program to recieve C source code and output them directly 
#in single step

#Shows the Command to be executed and the output together
#set -x

#echo 
#echo $*

options=$*

vim $pwd$options.java

#vim /home/ennova/$options.java;
#echo /////////////////// Java Program compilation \\\\\\\\\\\\\\\\\\  
echo
clear;
echo   Compiling $options.java ....  
javac $options.java; 
echo "Created $options.class" ; 
echo;

echo ---------------------- Start of Output --------------------------
java $*
echo
echo ---------------------- End of Output ----------------------------
#echo `//////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\`
#echo "$options.class deleted";
echo; echo
