#!/bin/bash
#Program to recieve C source code and output them directly 
#in single step

#Shows the Command to be executed and the output together
#set -x

#Accepts both "FileName" and "Filename.java" as inputs
options=`echo $* | sed 's/.java//'`

vim $pwd$options.java

clear;
echo ================= Java program compilation ======================
echo
echo  Compiling $options.java ....  
javac $options.java; 
echo  "Created $options.class" ; 
echo;

echo ---------------------- Start of Output --------------------------
java $*
echo ---------------------- End of Output ----------------------------
echo; 
echo;
