#!/bin/bash
#Program to recieve Java source code and compile, run the program, show output directly 

# Debugging the shell script#
#set -x


### Step to exection 
#   $ jj FILENAME     or      $ jj FILENAME.java
#   ----> opens the file given by vim editor
#   ----> When the file is saved and exited to Shell
#   ----> javac  is called
#   ----> If there was no errors, run the program


#set -x

#Accepts both "FileName" and "Filename.java" as inputs
options=`echo $* | sed 's/.java//'`

vim $pwd$options.java

clear;
echo ================= Java program compilation ======================
echo
echo  Compiling $options.java ....  
javac $options.java; 

#if  [ $? != 0 ]; then
#echo  "Created $options.class" ; 
#echo;
#fi

if [ $? = 0 ]; then
{
echo ---------------------- Start of Output --------------------------
java $options
echo ---------------------- End of Output ----------------------------
echo; 
echo;

}
fi
